# Generated by Django 5.2.17 on 2026-08-15 13:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="customer_type",
            field=models.CharField(
                choices=[("INDIVIDUAL", "شخصی"), ("ORGANIZATION", "سازمانی / اداره")],
                default="INDIVIDUAL",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="OrganizationDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center_name",
                    models.CharField(max_length=128, verbose_name="نام مرکز/اداره"),
                ),
                (
                    "manager_name",
                    models.CharField(max_length=128, verbose_name="نام مدیر/مسئول"),
                ),
                (
                    "manager_phone",
                    models.CharField(max_length=15, verbose_name="شماره مدیریت"),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار بررسی"),
                            ("APPROVED", "تأیید شده"),
                            ("REJECTED", "رد شده"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("verification_note", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_detail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProfileChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        choices=[
                            ("first_name", "نام"),
                            ("last_name", "نام خانوادگی"),
                            ("phone_number", "شماره موبایل"),
                            ("email", "ایمیل"),
                        ],
                        max_length=32,
                    ),
                ),
                ("old_value", models.CharField(blank=True, max_length=128)),
                ("new_value", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار تأیید"),
                            ("APPROVED", "تأیید شده"),
                            ("REJECTED", "رد شده"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("review_note", models.CharField(blank=True, max_length=255)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
