# Generated by Django 5.2.17 on 2026-08-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_customer_type_organizationdetail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                default="یاسوج",
                help_text="شهر انتخابی کاربر هنگام ثبت\u200cنام — برای نمایش هویت محلی صفحه اصلی (نام باید با locations.City.name یکی باشد)",
                max_length=64,
            ),
        ),
    ]
