# Generated by Django 5.2.17 on 2026-08-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="national_id",
            field=models.CharField(
                blank=True,
                help_text="کد ملی ۱۰ رقمی — فقط برای کاربرانی که از مسیر جدید (OTP) ثبت\u200cنام کرده\u200cاند الزامی است؛ حساب\u200cهای قدیمی\u200cتر می\u200cتوانند خالی باشند.",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
    ]
