# Generated by Django 5.2.17 on 2026-08-15 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("national_id", models.CharField(blank=True, max_length=10)),
                (
                    "national_card_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="collectors/national_card/"
                    ),
                ),
                (
                    "license_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="collectors/license/"
                    ),
                ),
                ("city", models.CharField(default="یاسوج", max_length=64)),
                (
                    "service_area",
                    models.CharField(
                        blank=True, help_text="محدوده فعالیت", max_length=255
                    ),
                ),
                ("bank_account_number", models.CharField(blank=True, max_length=32)),
                ("sheba_number", models.CharField(blank=True, max_length=26)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار بررسی"),
                            ("UNDER_REVIEW", "در حال بررسی"),
                            ("APPROVED", "تأیید شده"),
                            ("REJECTED", "رد شده"),
                            ("SUSPENDED", "معلق"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("verification_note", models.CharField(blank=True, max_length=255)),
                ("is_online", models.BooleanField(default=False)),
                (
                    "current_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "current_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "rating_avg",
                    models.DecimalField(decimal_places=2, default=5, max_digits=3),
                ),
                ("completed_jobs", models.PositiveIntegerField(default=0)),
                ("cancelled_jobs", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collector_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CollectorDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("NATIONAL_CARD", "کارت ملی"),
                            ("LICENSE", "گواهینامه"),
                            ("VEHICLE_CARD", "کارت خودرو"),
                            ("OTHER", "سایر"),
                        ],
                        max_length=16,
                    ),
                ),
                ("file", models.FileField(upload_to="collectors/documents/")),
                ("verified", models.BooleanField(default=False)),
                (
                    "collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="collectors.collectorprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand", models.CharField(blank=True, max_length=64)),
                ("model", models.CharField(blank=True, max_length=64)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("plate_number", models.CharField(max_length=20)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("PICKUP", "وانت"),
                            ("MOTORCYCLE", "موتور"),
                            ("VAN", "ون"),
                            ("TRUCK", "کامیونت"),
                        ],
                        default="PICKUP",
                        max_length=16,
                    ),
                ),
                (
                    "capacity_kg",
                    models.DecimalField(decimal_places=1, default=100, max_digits=8),
                ),
                ("color", models.CharField(blank=True, max_length=32)),
                (
                    "vehicle_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="collectors/vehicles/"
                    ),
                ),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                (
                    "technical_inspection_expiry",
                    models.DateField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="collectors.collectorprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
