# Generated by Django 5.2.17 on 2026-08-15 07:23

import django.db.models.deletion
import orders.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0001_initial"),
        ("materials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("COLLECTION", "جمع\u200cآوری شهروند"),
                            ("MARKETPLACE", "فروش در بازارگاه"),
                            ("FACTORY", "سفارش کارخانه"),
                        ],
                        default="MARKETPLACE",
                        max_length=16,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Optional: restrict to a seller role",
                        max_length=32,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=64)),
                ("percent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rules",
                        to="materials.material",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=orders.models.generate_order_code,
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=0, default=0, max_digits=14),
                ),
                (
                    "commission_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=14),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=0, default=0, max_digits=14),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "پرداخت\u200cنشده"),
                            ("PAID", "پرداخت شده"),
                            ("REFUNDED", "بازگشت وجه"),
                        ],
                        default="UNPAID",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار"),
                            ("CONFIRMED", "تأیید شده"),
                            ("PROCESSING", "در حال پردازش"),
                            ("READY_FOR_PICKUP", "آماده تحویل"),
                            ("IN_TRANSIT", "در حال ارسال"),
                            ("DELIVERED", "تحویل داده شده"),
                            ("COMPLETED", "تکمیل شده"),
                            ("CANCELLED", "لغو شده"),
                            ("REFUNDED", "بازگشت وجه"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_as_buyer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="marketplace.listing",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="marketplace.offer",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_as_seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommissionTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "percent_applied",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=14)),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.commissionrule",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_transaction",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity_kg", models.DecimalField(decimal_places=1, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=0, max_digits=12)),
                ("line_total", models.DecimalField(decimal_places=0, max_digits=14)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="materials.material",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
