# Generated by Django 5.2.17 on 2026-08-15 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=0, default=0, help_text="Toman", max_digits=14
                    ),
                ),
                (
                    "pending_balance",
                    models.DecimalField(decimal_places=0, default=0, max_digits=14),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CREDIT", "واریز"),
                            ("DEBIT", "برداشت"),
                            ("WITHDRAWAL", "درخواست برداشت"),
                            ("PURCHASE", "خرید"),
                            ("SALE", "فروش"),
                            ("REWARD", "پاداش"),
                            ("COMMISSION", "کمیسیون"),
                            ("REFUND", "بازگشت وجه"),
                        ],
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=14)),
                ("balance_after", models.DecimalField(decimal_places=0, max_digits=14)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="e.g. collection request code, order code",
                        max_length=64,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=14)),
                ("sheba_number", models.CharField(blank=True, max_length=26)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار بررسی"),
                            ("APPROVED", "تأیید شد"),
                            ("REJECTED", "رد شد"),
                            ("PAID", "پرداخت شد"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
