# Generated by Django 5.2.17 on 2026-08-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("CREDIT", "واریز"),
                    ("DEBIT", "برداشت"),
                    ("WITHDRAWAL", "درخواست برداشت"),
                    ("PURCHASE", "خرید"),
                    ("SALE", "فروش"),
                    ("REWARD", "پاداش"),
                    ("COMMISSION", "کمیسیون"),
                    ("REFUND", "بازگشت وجه"),
                    ("GREEN_IMPACT", "مشارکت اثر سبز"),
                ],
                max_length=16,
            ),
        ),
    ]
