# Generated by Django 5.2.17 on 2026-08-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceAreaQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area_name",
                    models.CharField(
                        help_text="باید دقیقاً با مقدار فیلد «شهر» (city) پروفایل راننده یکسان باشد",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "max_collectors",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="حداکثر تعداد راننده در وضعیت در انتظار/تأییدشده در این منطقه — خالی یعنی بدون محدودیت",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "سقف ظرفیت راننده در منطقه",
                "verbose_name_plural": "سقف ظرفیت راننده در مناطق",
            },
        ),
    ]
