# Generated by Django 5.2.17 on 2026-08-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="requires_appraisal",
            field=models.BooleanField(
                default=False,
                help_text="No fixed per-kg price — value depends on inspection (e.g. mixed e-waste boards, tires). Frontend shows 'قیمت پس از کارشناسی' instead of a number.",
            ),
        ),
    ]
