# Generated by Django 5.2.17 on 2026-08-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialprice",
            name="market_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Toman — قیمت مرجع بازار آزاد برای همان واحد (اختیاری، صرفاً جهت مقایسه در «قیمت روز»)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="materialprice",
            name="price_per_unit",
            field=models.DecimalField(
                decimal_places=0,
                help_text="Toman — قیمت خرید سبزینو از شهروند",
                max_digits=12,
            ),
        ),
    ]
