# Generated by Django 5.2.17 on 2026-08-17 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wallet", "0002_alter_wallettransaction_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorePartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FOOD", "خوراکی و سوپرمارکت"),
                            ("HOUSEHOLD", "لوازم خانه"),
                            ("DIGITAL", "دیجیتال و شارژ"),
                            ("HEALTH", "سلامت و آرایشی"),
                            ("SERVICES", "خدمات"),
                            ("OTHER", "سایر"),
                        ],
                        default="OTHER",
                        max_length=16,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="store/partners/"
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "redeem_instructions",
                    models.TextField(
                        blank=True,
                        help_text="راهنمای استفاده برای شهروند — مثلاً «کد را هنگام خرید حضوری به فروشنده نشان دهید»",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="StoreRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار بررسی"),
                            ("APPROVED", "تأیید شد"),
                            ("REJECTED", "رد شد"),
                            ("FULFILLED", "استفاده شد"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("redemption_code", models.CharField(blank=True, max_length=12)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="store.storepartner",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_redemptions",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
