# Generated by Django 5.2.17 on 2026-08-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_city_has_identity_city_hero_tagline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="service_radius_km",
            field=models.PositiveIntegerField(
                default=30,
                help_text="شعاع سرویس\u200cدهی (کیلومتر) از مرکز شهر — آدرس\u200cهای خارج از این شعاع هنگام ثبت درخواست/آدرس رد می\u200cشوند.",
            ),
        ),
    ]
