# Generated by Django 5.2.17 on 2026-08-22 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_city_has_identity_city_hero_tagline_and_more"),
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recyclingstation",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="نقشهٔ هر کاربر فقط ایستگاه\u200cهای همین شهر را نشان می\u200cدهد — خالی یعنی در فیلتر شهری نمایش داده نمی\u200cشود.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stations",
                to="locations.city",
            ),
        ),
    ]
