# Generated by Django 5.2.17 on 2026-08-15 07:23

import collection_requests.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("collectors", "0001_initial"),
        ("materials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=collection_requests.models.generate_request_code,
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "amount_range",
                    models.CharField(
                        choices=[
                            ("UNDER_5", "کمتر از ۵ کیلو"),
                            ("R5_10", "۵ تا ۱۰ کیلو"),
                            ("R10_20", "۱۰ تا ۲۰ کیلو"),
                            ("R20_50", "۲۰ تا ۵۰ کیلو"),
                            ("R50_100", "۵۰ تا ۱۰۰ کیلو"),
                            ("OVER_100", "بیشتر از ۱۰۰ کیلو"),
                        ],
                        max_length=16,
                    ),
                ),
                ("address_text_snapshot", models.CharField(blank=True, max_length=255)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("preferred_time", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="collection_requests/photos/"
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Toman, computed at creation",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "ثبت شده"),
                            ("SEARCHING_COLLECTOR", "در جستجوی جمع\u200cآور"),
                            ("ASSIGNED", "تخصیص یافته"),
                            ("ACCEPTED", "پذیرفته شده"),
                            ("ON_THE_WAY", "در مسیر"),
                            ("ARRIVED", "رسیده"),
                            ("COLLECTED", "جمع\u200cآوری شده"),
                            ("WEIGHING", "در حال وزن\u200cکشی"),
                            ("COMPLETED", "تکمیل شده"),
                            ("CANCELLED", "لغو شده"),
                        ],
                        default="REQUESTED",
                        max_length=24,
                    ),
                ),
                ("cancelled_reason", models.CharField(blank=True, max_length=255)),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_requests",
                        to="accounts.address",
                    ),
                ),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "materials",
                    models.ManyToManyField(
                        related_name="collection_requests", to="materials.material"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("on_the_way_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="collectors.collectorprofile",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment",
                        to="collection_requests.collectionrequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CollectionStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "ثبت شده"),
                            ("SEARCHING_COLLECTOR", "در جستجوی جمع\u200cآور"),
                            ("ASSIGNED", "تخصیص یافته"),
                            ("ACCEPTED", "پذیرفته شده"),
                            ("ON_THE_WAY", "در مسیر"),
                            ("ARRIVED", "رسیده"),
                            ("COLLECTED", "جمع\u200cآوری شده"),
                            ("WEIGHING", "در حال وزن\u200cکشی"),
                            ("COMPLETED", "تکمیل شده"),
                            ("CANCELLED", "لغو شده"),
                        ],
                        max_length=24,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="collection_requests.collectionrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeighingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "unit_price_snapshot",
                    models.DecimalField(decimal_places=0, max_digits=12),
                ),
                ("total_value", models.DecimalField(decimal_places=0, max_digits=12)),
                ("points_awarded", models.IntegerField(default=0)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weighing_records",
                        to="materials.material",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weighing",
                        to="collection_requests.collectionrequest",
                    ),
                ),
                (
                    "weighed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
