# Generated by Django 5.2.17 on 2026-08-15 13:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_customer_type_organizationdetail_and_more"),
        ("collection_requests", "0001_initial"),
        ("materials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "هفتگی"),
                            ("BIWEEKLY", "دو هفته یک\u200cبار"),
                            ("MONTHLY", "ماهانه"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="۰=شنبه ... ۶=جمعه، برای هفتگی/دوهفته\u200cیک\u200cبار",
                        null=True,
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="برای ماهانه، ۱ تا ۲۸", null=True
                    ),
                ),
                ("preferred_hour", models.PositiveSmallIntegerField(default=9)),
                ("is_active", models.BooleanField(default=True)),
                ("next_run_date", models.DateField()),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_schedules",
                        to="accounts.address",
                    ),
                ),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_generated_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="collection_requests.collectionrequest",
                    ),
                ),
                (
                    "materials",
                    models.ManyToManyField(
                        related_name="recurring_schedules", to="materials.material"
                    ),
                ),
            ],
            options={
                "ordering": ["next_run_date"],
            },
        ),
        migrations.CreateModel(
            name="CollectionRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="وزن تقریبی (اهرم) یا دقیق کیلوگرم",
                        max_digits=8,
                    ),
                ),
                (
                    "is_exact",
                    models.BooleanField(
                        default=False,
                        help_text="کاربر وزن را دقیق وارد کرده یا فقط اهرم را جابه\u200cجا کرده",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="request_items",
                        to="materials.material",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="collection_requests.collectionrequest",
                    ),
                ),
            ],
            options={
                "unique_together": {("request", "material")},
            },
        ),
    ]
