# Generated by Django 5.2.17 on 2026-08-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_requests", "0002_recurringschedule_collectionrequestitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionrequest",
            name="green_intent",
            field=models.CharField(
                choices=[
                    ("SELL", "فروش (واریز به کیف\u200cپول)"),
                    ("DONATE", "کمک به اثر سبز"),
                ],
                default="SELL",
                help_text="ترجیح غیرالزام\u200cآور شهروند هنگام ثبت درخواست — فقط پیش\u200cفرض تخصیص «اثر سبز» پس از وزن\u200cکشی را تعیین می\u200cکند؛ مبلغ و سهم نهایی همچنان اختیاری و پس از وزن\u200cکشی مشخص می\u200cشود.",
                max_length=8,
            ),
        ),
    ]
