# Generated by Django 5.2.17 on 2026-08-18 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_requests", "0003_collectionrequest_green_intent"),
        ("collectors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestDismissal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dismissed_requests",
                        to="collectors.collectorprofile",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dismissals",
                        to="collection_requests.collectionrequest",
                    ),
                ),
            ],
            options={
                "unique_together": {("request", "collector")},
            },
        ),
    ]
