# Generated by Django 5.2.17 on 2026-08-15 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("national_id", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(default="یاسوج", max_length=64)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار بررسی"),
                            ("APPROVED", "تأیید شده"),
                            ("REJECTED", "رد شده"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "documents",
                    models.FileField(
                        blank=True, null=True, upload_to="marketplace/documents/"
                    ),
                ),
                ("business_type", models.CharField(blank=True, max_length=64)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("national_id", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(default="یاسوج", max_length=64)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار بررسی"),
                            ("APPROVED", "تأیید شده"),
                            ("REJECTED", "رد شده"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "documents",
                    models.FileField(
                        blank=True, null=True, upload_to="marketplace/documents/"
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=128)),
                (
                    "purchase_capacity_kg_month",
                    models.DecimalField(decimal_places=1, default=0, max_digits=12),
                ),
                ("coverage_area", models.CharField(blank=True, max_length=255)),
                (
                    "minimum_order_kg",
                    models.DecimalField(decimal_places=1, default=0, max_digits=10),
                ),
                (
                    "materials_needed",
                    models.ManyToManyField(
                        blank=True, related_name="factories", to="materials.material"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("quantity_kg", models.DecimalField(decimal_places=1, max_digits=10)),
                ("price_per_kg", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "minimum_order_kg",
                    models.DecimalField(decimal_places=1, default=1, max_digits=10),
                ),
                ("quality", models.CharField(blank=True, max_length=64)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "پیش\u200cنویس"),
                            ("ACTIVE", "فعال"),
                            ("RESERVED", "رزرو شده"),
                            ("SOLD", "فروخته شده"),
                            ("EXPIRED", "منقضی"),
                            ("CANCELLED", "لغو شده"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="materials.material",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="marketplace/listings/")),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="marketplace.listing",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("quantity_kg", models.DecimalField(decimal_places=1, max_digits=12)),
                (
                    "target_price_per_kg",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=12, null=True
                    ),
                ),
                ("coverage_area", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "باز"),
                            ("FULFILLED", "تکمیل شده"),
                            ("CANCELLED", "لغو شده"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requests",
                        to="materials.material",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("quantity_kg", models.DecimalField(decimal_places=1, max_digits=12)),
                ("price_per_kg", models.DecimalField(decimal_places=0, max_digits=12)),
                ("message", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار"),
                            ("ACCEPTED", "پذیرفته شده"),
                            ("REJECTED", "رد شده"),
                            ("WITHDRAWN", "پس گرفته شده"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="marketplace.purchaserequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecyclingCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("national_id", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(default="یاسوج", max_length=64)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار بررسی"),
                            ("APPROVED", "تأیید شده"),
                            ("REJECTED", "رد شده"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "documents",
                    models.FileField(
                        blank=True, null=True, upload_to="marketplace/documents/"
                    ),
                ),
                (
                    "materials_processed",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recycling_centers",
                        to="materials.material",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Wholesaler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("national_id", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(default="یاسوج", max_length=64)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار بررسی"),
                            ("APPROVED", "تأیید شده"),
                            ("REJECTED", "رد شده"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "documents",
                    models.FileField(
                        blank=True, null=True, upload_to="marketplace/documents/"
                    ),
                ),
                (
                    "materials_of_interest",
                    models.ManyToManyField(
                        blank=True, related_name="wholesalers", to="materials.material"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
