# Generated by Django 5.2.17 on 2026-08-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="has_identity",
            field=models.BooleanField(
                default=False,
                help_text="فعال\u200cسازی هویت بصری اختصاصی این شهر در صفحه اصلی",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="hero_tagline",
            field=models.CharField(
                blank=True, help_text="شعار کوتاه هویت محلی این شهر", max_length=140
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="landmark_icon",
            field=models.CharField(
                blank=True, help_text="ایموجی نمادین لندمارک، مثلاً 🏔️", max_length=8
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="landmark_name",
            field=models.CharField(
                blank=True,
                help_text="مثلاً کوه دنا / تخت جمشید / سی\u200cوسه\u200cپل",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="theme_color_from",
            field=models.CharField(
                blank=True,
                help_text="کد رنگ hex شروع گرادیان، مثلاً #0f4d2e",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="theme_color_to",
            field=models.CharField(
                blank=True,
                help_text="کد رنگ hex پایان گرادیان، مثلاً #16a34a",
                max_length=9,
            ),
        ),
    ]
