# Generated by Django 5.2.17 on 2026-08-17 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("collection_requests", "0002_recurringschedule_collectionrequestitem"),
        ("locations", "0002_city_has_identity_city_hero_tagline_and_more"),
        ("wallet", "0002_alter_wallettransaction_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpactProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("EMPLOYMENT", "اشتغال سبز"),
                            ("SOCIAL", "حمایت اجتماعی"),
                            ("ENVIRONMENT", "محیط\u200cزیست"),
                            ("LOCAL", "توسعه محلی"),
                        ],
                        max_length=16,
                    ),
                ),
                ("icon", models.CharField(default="🌱", max_length=16)),
                (
                    "summary",
                    models.CharField(
                        blank=True, help_text="یک\u200cخطی برای کارت", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="هدف کامل طرح")),
                (
                    "operator_name",
                    models.CharField(
                        blank=True, help_text="مجری/مجموعه مسئول", max_length=128
                    ),
                ),
                (
                    "goal_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="تومان — خالی یعنی طرح مستمر بدون سقف مشخص (مثل اشتغال سبز)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "raised_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "فعال"),
                            ("PAUSED", "متوقف"),
                            ("COMPLETED", "تکمیل\u200cشده"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "progress_report",
                    models.TextField(
                        blank=True, help_text="گزارش پیشرفت طرح — قابل ویرایش توسط مدیر"
                    ),
                ),
                (
                    "impact_report",
                    models.TextField(blank=True, help_text="گزارش اثر واقعی ایجادشده"),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        default=True,
                        help_text="داده نمونه — تا جایگزینی با پروژه واقعی از پنل مدیریت",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="برای دسته «توسعه محلی» — شهر مرتبط",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="impact_projects",
                        to="locations.city",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImpactContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=14)),
                (
                    "waste_value_snapshot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="ارزش کل همان درخواست در لحظهٔ مشارکت (برای رسید)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        help_text="اگر مشارکت بلافاصله پس از یک تحویل مشخص ثبت شده باشد",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="impact_contributions",
                        to="collection_requests.collectionrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impact_contributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wallet.wallettransaction",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contributions",
                        to="green_impact.impactproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
