# Generated by Django 5.2.17 on 2026-08-22 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_requests", "0004_requestdismissal"),
        ("green_impact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="impactproject",
            name="is_default_allocation",
            field=models.BooleanField(
                default=False,
                help_text="اگر شهروند تا یک هفته پس از «کمک به اثر سبز» تخصیص را انتخاب نکند، مبلغ خودکار به این طرح می\u200cرود. فقط یک طرح باید این گزینه را فعال داشته باشد.",
            ),
        ),
        migrations.CreateModel(
            name="PendingDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=14)),
                ("deadline", models.DateTimeField()),
                (
                    "resolved",
                    models.BooleanField(
                        default=False,
                        help_text="یا شهروند دستی تخصیص داد، یا خودکار به طرح پیش\u200cفرض رفت",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_donation",
                        to="collection_requests.collectionrequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
