# Generated by Django 5.2.17 on 2026-08-15 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="emoji or icon key used by the frontend",
                        max_length=32,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Material categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[("kg", "کیلوگرم"), ("piece", "عدد")],
                        default="kg",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                ("accepted_at_stations", models.BooleanField(default=True)),
                (
                    "co2_kg_saved_per_kg",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Configurable estimate used for the environmental-impact widgets (not scientific fact).",
                        max_digits=6,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="materials.materialcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
