# Generated by Django 5.2.17 on 2026-08-15 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "context_type",
                    models.CharField(
                        choices=[
                            ("COLLECTION", "جمع\u200cآوری (شهروند ↔ جمع\u200cآور)"),
                            ("ORDER", "سفارش بازارگاه (خریدار ↔ فروشنده)"),
                            ("STATION", "تحویل به ایستگاه (شهروند ↔ ایستگاه)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="کد درخواست/سفارش/تراکنش مربوطه", max_length=32
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(help_text="۱ تا ۵")),
                ("comment", models.CharField(blank=True, max_length=255)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("from_user", "context_type", "reference")},
            },
        ),
    ]
